apiVersion: v1
kind: Service
metadata:
  name: hellojs
  namespace: javascript 
  labels:
    app: hellojs_app
spec:
  type: ClusterIP
  selector:
    app: hellojs_app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellojs
  namespace: javascript
  labels:
    app: hellojs_app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellojs_app
  template:
    metadata:
      labels:
        app: hellojs_app
    spec:
      containers:
      - name: hellojs-app
        image: mvijay/hellojs_app
        ports:
        - containerPort: 3000
