kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "moodle.fullname" . }}-moodle
  labels: {{- include "moodle.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
