apiVersion: v1
kind: Service
metadata:
  name: {{ include "moodle.fullname" . }}
  labels: {{- include "moodle.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
    - name: https
      port: {{ .Values.service.httpsPort }}
      targetPort: https
      protocol: TCP
  selector: {{- include "moodle.selectorLabels" . | nindent 4 }}
